name: "Lint PR"

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited

permissions:
  pull-requests: read

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    steps:
    - name: Validate PR Title
      run: |
        if [[ ! "${{ github.event.pull_request.title }}" =~ ^(TD|TT)-[0-9]+: ]]; then
          echo "PR title does not start with a valid Jira ticket (TD- or TT-) followed by a colon. Please include a ticket like 'TD-123: Description' or 'TT-456: Description'." >&2
          exit 1
        fi
      shell: bash