name: E2E Tests

on:
  push:
    branches:
      - main
      - TD-3857-bump-operator-framework-for-rediskun
  pull_request:
    branches:
      - main

jobs:
  e2e:
    runs-on: ubuntu-latest
    env:
      IMG: tykio/redis-cluster-operator:v0.0.0-teste2e
      KIND_CLUSTER: e2e-test

    steps:
    # common steps for both tests
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set up Kind cluster
        uses: engineerd/setup-kind@v0.6.2
        with:
          version: "v0.27.0"
          image: "kindest/node:v1.31.6"
          name: ${{ env.KIND_CLUSTER }}

      - name: Verify cluster is running
        run: |
          kubectl cluster-info
          kubectl get nodes

      # run the drc_operator e2e tests
      - name: Run Redis Cluster Operator E2E Tests
        run: |
          go test ./test/e2e/drc_operator -v -ginkgo.v

      # steps for drc_crud test
      - name: Load Docker image into Kind cluster
        run: |
          kind load docker-image ${{ env.IMG }} --name e2e-test

      - name: Install CRDs
        run: |
          make install

      - name: Deploy controller-manager (operator)
        run: |
          make deploy IMG=${{ env.IMG }}

      - name: Wait for operator to become available
        run: |
          kubectl wait --for=condition=available --timeout=90s deployment/redis-cluster-operator-controller-manager
          --namespace redis-cluster-operator-system
      # Run the drc_crud tests
      - name: Run Redis Cluster CRUD E2E Tests
        run: |
          go test ./test/e2e/drc_crud -v -ginkgo.v
